### ISSUE TITLE
corpus_bleu() got an unexpected keyword argument 'sys_stream'

### ISSUE THREAD

**Issue by James-Havinga99** [joeynmt/joeynmt#155]
Got this error when trying to run a English to Afrikaans training on google colab. I used the exact copy of the colab provided in the masakhane-mt readme, just changing the target language to Afrikaans. The model starts training but before it finished one epoch I get the error. I did some searching online but wasn't able to find anything about this error. This is a screenshot of the full error I am getting:
![Screenshot_1](https://user-images.githubusercontent.com/79093414/129165081-2e776f79-c4f3-4074-95dd-1aaa2418dd2a.png)

**Comment by bricksdont** [comment]
This is because of breaking changes in SacreBLEU 2.0. This keyword is now called "hypotheses":

https://github.com/mjpost/sacrebleu/commit/078c440168c6adc89ba75fe6d63f0d922d42bcfe#diff-2553a315bb1f7e68c9c1b00d56eaeb74f5205aeb3a189bc3e527b122c6078795L11

Fixes would be to change the keyword in joeynmt/metrics, or pin the sacrebleu version to `<2.0.0.`

**Comment by James-Havinga99** [comment]
Perfect downgrading sacrebleu fixed the issue. Thanks very much for your help!

**Comment by bricksdont** [comment]
You're welcome James, but please do not close this issue yet :-). This needs to be fixed permanently in Joey.

**Comment by KashyapKishore** [comment]
Hi,
though sys_stream error is gone after downgrading now another error is showing as 
![Screenshot 2021-08-14 at 10 37 48 PM](https://user-images.githubusercontent.com/36396901/129454982-a7a8b3ae-1bb5-45cf-bfcb-97cc1ecaadbf.png)

**Comment by may-** [comment]
Hi, it must be related to my pull request that Julia accepted right now. I'll look into it and fix it as soon as possible. For now, please roll back to the commit hash [c53f64e](https://github.com/joeynmt/joeynmt/commit/c53f64e1910fb65f51a078dbd39d78d2fa16e26a).
Sorry for the confusion!

**Comment by KashyapKishore** [comment]
Thanks may, will check it.

**Comment by may-** [comment]
Can I ask about your environment? I tested my pull request in the following setup:

- python 3.9
- cuda 10.2
- pytorch 1.9.0
- torchtext 0.10.0
- numpy 1.20.1
- pylint 2.9.6

**Comment by KashyapKishore** [comment]
Hi,
Yes, my environment is 
- python 3.7.11
- cuda 11.0
- numpy 1.20.1
- setuptools 41.0.0
- torch 1.9.0
- torchtext 0.10.0
- sacrebleu 1.5.1
- pylint 2.9.6
- wrapt 1.11.1

**Comment by KashyapKishore** [comment]
Hi may,

I think you have rectified the issue few minutes back?

**Comment by may-** [comment]
I fixed the bug: https://github.com/may-/joeynmt/commit/2169a050667b3d9c41369cb4babf4cba0f913827.
I started a test, let's see if it works... If the test goes well, I'll open a pull request. maybe tomorrow.

**Comment by KashyapKishore** [comment]
Thank you, it is working now.

**Comment by may-** [comment]
FYI @juliakreutzer

**Comment by James-Havinga99** [comment]
Hi there,
I'm trying to run the training again today and I still seem to be running into issues. I've updated my torch version to 1.9.0+cu102. And I'm using sacreblue 2.0.0. But I am still getting the 'sys_stream' error:
![Screenshot_3](https://user-images.githubusercontent.com/79093414/129574086-15d0b36c-07d7-42f1-841c-91357f75da07.png)
And then if I downgrade the sacreblue version to 1.5.1 I get the '_heappushpop_max' error: 
![Screenshot_4](https://user-images.githubusercontent.com/79093414/129574206-a6437f09-3cea-4eb5-8915-fe36230bf230.png)
Not sure if I'm doing something wrong here ?

**Comment by may-** [comment]
Hi,
the fix is not merged yet to the master branch. Can you please cherry-pick this? https://github.com/joeynmt/joeynmt/pull/156/files

**Comment by bricksdont** [comment]
@may- Did the commits that introduced this issue about heapq pass the CI build before merging? If so, do the tests need to be extended?

**Comment by may-** [comment]
@bricksdont 
Ah, you presumably mean the unittest on `sacrebleu.corpus_chrf()`, don't you? `sacrebleu.corpus_chrf()` returns now (in v2.0) the score between 0 and 100, so I changed joeynmt's metrics.chrf() to return score / 100. I checked my pull request https://github.com/joeynmt/joeynmt/pull/156 passed all the unittests in travis CI.

Do you mean, I shouldn't change the return value of `metrics.chrf()` but the unittest to check score * 100? Or do you mean something else??

If you mean I should write a unit test for the new heap queue used in ckpt path rotation, then ok, I'll write it :)

**Comment by gsarti** [comment]
Another problem seemingly related to the update of SacreBLEU 2.0 is that now ChrF scores are rescaled and make the unit tests fail. This should be easily fixed by updating the tests to the new scale. This is the result of `python3 -m unittest` after a fresh clone + install:

![image](https://user-images.githubusercontent.com/16674069/132123525-cd26076a-04f9-46bc-945c-87f23945f285.png)

**Comment by may-** [comment]
@gsarti 
I changed the return value of `chrf()` in my bug fix https://github.com/joeynmt/joeynmt/pull/156/files, so that the current joeynmt's behavior won't change. Do you think we should follow the sacrebleu's update and change the unittest instead?

**Comment by gsarti** [comment]
@may-  maybe it would be more intuitive for sacrebleu users, but I think either way is fine!
